htmLaTeX: DocumentData Class Reference
DocumentData Class Reference
This class provides a well-formed XML representation of a single input document.
#include <documentdata.h>
Public Types
enum FileType {
JavaDocHTML, HTML, Tex, PDF,
Unknown
}
Public Member Functions
DocumentData (QFileInfo fileinfo, Node *node, FileType filetype)
This is the only constructor.
QString text ()
This method returns a well-formed XML representation of the underlying input document.
QFileInfo fileInfo () const
This method returns a QFileInfo object which holds detailed information about the input document.
Node * node () const
The application's internal tree structure is supposed to represent a whole input document including its subdocuments.
Private Member Functions
void _preprocessingHook ()
This hook-method calls all preprocessing methods.
void _preprocessHTML ()
This method changes the specified HTML-file in order to gain well-formed XML (XHTML).
Private Attributes
QString _text
This attribute contains a well-formed XML representation of the underlying input document.
QFileInfo _fileInfo
This attribute holds detailed information about the input document.
FileType _fileType
This attribute contains the file type of the input document (i.e.
Node * _node
The application's internal tree structure is supposed to represent a whole input document including its subdocuments.
bool _preprocessed
This attribute indicates whether or not the input document has already been preprocessed by the appropriate preprocessing method.
Detailed Description
This class provides a well-formed XML representation of a single input document.
Author:
Bjoern
Definition at line 18 of file documentdata.h.
Member Enumeration Documentation
enum DocumentData::FileType
Enumerator:
JavaDocHTML
HTML
Tex
PDF
Unknown
Definition at line 22 of file documentdata.h.
Constructor & Destructor Documentation
DocumentData::DocumentData (QFileInfo fileinfo, Node * node, FileType filetype)
This is the only constructor.
It returns an object created from a QFileInfo object which holds detailed information about a single input document such as its absolute file path. The text() method returns a well-formed XML representation of the input document taking the file type into account. The application's internal tree structure is supposed to represent a whole input document including its subdocuments. So a Node object is used by the DocumentReader to determine where to add the subdocument represented by this class (DocumentData).
Parameters:
<fileinfo> holds detailed information about the input document.
Parameters:
<node> is the corresponding parent node in the application's internal tree structure.
Parameters:
<filetype> indicates the file typ of the input document (i.e. JavaDoc HTML).
Author:
Bjoern
Definition at line 3 of file documentdata.cpp.
References _fileType, and _node.
Member Function Documentation
void DocumentData::_preprocessHTML () [private]
This method changes the specified HTML-file in order to gain well-formed XML (XHTML).
Author:
Bjoern
Definition at line 13 of file documentdata.cpp.
References _fileInfo, _fileType, _preprocessed, _text, Settings::DEBUG, and JavaDocHTML.
Referenced by _preprocessingHook().
void DocumentData::_preprocessingHook () [private]
This hook-method calls all preprocessing methods.
Author:
Bjoern
Definition at line 9 of file documentdata.cpp.
References _preprocessHTML().
Referenced by text().
QFileInfo DocumentData::fileInfo () const
This method returns a QFileInfo object which holds detailed information about the input document.
Author:
Bjoern
Definition at line 68 of file documentdata.cpp.
References _fileInfo.
Referenced by DocumentReader::read().
Node * DocumentData::node () const
The application's internal tree structure is supposed to represent a whole input document including its subdocuments.
So the Node object is used by the DocumentReader to determine where to add the subdocument represented by this class (DocumentData).
Author:
Bjoern
Definition at line 72 of file documentdata.cpp.
References _node.
Referenced by DocumentReader::read().
QString DocumentData::text ()
This method returns a well-formed XML representation of the underlying input document.
Author:
Bjoern
Definition at line 61 of file documentdata.cpp.
References _preprocessed, _preprocessingHook(), and _text.
Referenced by DocumentReader::read().
Member Data Documentation
QFileInfo DocumentData::_fileInfo [private]
This attribute holds detailed information about the input document.
Author:
Bjoern
Definition at line 48 of file documentdata.h.
Referenced by _preprocessHTML(), and fileInfo().
FileType DocumentData::_fileType [private]
This attribute contains the file type of the input document (i.e.
JavaDoc HTML).
Author:
Bjoern
Definition at line 53 of file documentdata.h.
Referenced by _preprocessHTML(), and DocumentData().
Node* DocumentData::_node [private]
The application's internal tree structure is supposed to represent a whole input document including its subdocuments.
So the Node object is used by the DocumentReader to determine where to add the subdocument represented by this class (DocumentData).
Author:
Bjoern
Definition at line 60 of file documentdata.h.
Referenced by DocumentData(), and node().
bool DocumentData::_preprocessed [private]
This attribute indicates whether or not the input document has already been preprocessed by the appropriate preprocessing method.
Author:
Bjoern
Definition at line 65 of file documentdata.h.
Referenced by _preprocessHTML(), and text().
QString DocumentData::_text [private]
This attribute contains a well-formed XML representation of the underlying input document.
Author:
Bjoern
Definition at line 44 of file documentdata.h.
Referenced by _preprocessHTML(), and text().
The documentation for this class was generated from the following files:
documentdata.h
documentdata.cpp