htmLaTeX: DocumentReader Class Reference
DocumentReader Class Reference
The DocumentReader class creates the application's internal tree structure from a specified input document and is able to include referenced subdocuments.
#include <documentreader.h>
Public Member Functions
DocumentReader (TranslationMapper *translationmapper)
This is the only constructor.
Node * read (QString indexfilepath, DocumentData::FileType filetype)
This method creates a Node tree structure which corresponds to the whole input document including its subdocuments if desired (_includeSubDocuments is set).
Private Member Functions
void _readElement (QDomElement element, Node *node)
This method processes a single document recursively.
Private Attributes
TranslationMapper * _translationMapper
The _translationMapper provides two data objects: firstly a DocumentReaderData object which is used by the DocumentReader and secondly a key-value-pair structure which is used by the Converter.
QFileInfo _indexFileInfo
This attribute provides detailed information about the input index file such as absolute and relative path etc.
DocumentData::FileType _fileType
This attribute indicates of which type the input document is.
QStack< DocumentData * > _documentStack
This stack is populated with DocumentData objects when processing the input document.
bool _includeSubDocuments
This attribute indicates whether or not subdocuments are included by the input document processing.
Detailed Description
The DocumentReader class creates the application's internal tree structure from a specified input document and is able to include referenced subdocuments.
Author:
Bjoern
Definition at line 21 of file documentreader.h.
Constructor & Destructor Documentation
DocumentReader::DocumentReader (TranslationMapper * translationmapper)
This is the only constructor.
Parameters:
<translationmapper> is used to obtain a DocumentReaderData object which mainly describes how a reference to a another document is defined in the input document.
Author:
Bjoern
Definition at line 3 of file documentreader.cpp.
References _fileType, _includeSubDocuments, _translationMapper, Settings::getValue(), and DocumentData::Unknown.
Member Function Documentation
void DocumentReader::_readElement (QDomElement element, Node * node) [private]
This method processes a single document recursively.
It adds for each node of the input document a corresponding Node object to the application's internal tree structure. If a reference to a subdocument is found a new DocumentData object is generated and pushed on the _documentStack.
Parameters:
<element> is the current parent QDomElement object. Notice that the _readElement() method performs a recursion to process a single document.
Parameters:
<node> is a pointer pointing to the very Node object of the application's internal tree structure to which currently generated Node objects will be added. Notice that the _readElement() method performs a recursion to process a single document.
Author:
Bjoern
Definition at line 80 of file documentreader.cpp.
References _documentStack, _fileType, _includeSubDocuments, _indexFileInfo, _translationMapper, Node::addAttribute(), Node::addChild(), Settings::DEBUG, Node::getAttributes(), TranslationMapper::getDocumentReference(), Node::getLayer(), DocumentReaderData::getTagName(), DocumentReaderData::getUrlContainingAttributeName(), and Node::setContent().
Referenced by read().
Node * DocumentReader::read (QString indexfilepath, DocumentData::FileType filetype)
This method creates a Node tree structure which corresponds to the whole input document including its subdocuments if desired (_includeSubDocuments is set).
This method starts by pushing a DocumentData object created from the index document to the _documentStack.
The nodes of each document are processed recursively by the _readElement() method. Whereas the documents (subdocuments) are processed in an iteration loop by means of the _documentStack.
Parameters:
<indexfilepath> contains the absolute file path to the index document.
Parameters:
<filetype> indicates of which type the input document is.
Author:
Bjoern
Then the iteration loop is started which ends when all DocumentData objects are popped from the _documentStack. Each DocumentData object contains a well-formed XML representaion of the underlying input document. Additionally it provides a pointer to the node of the application's internal tree structure to which the document will be added to. This XML representation is passed to a QDomDocument object which validates it and retrieves the root element. Then the _readElement() method processes the document with the given root element.
Author:
Bjoern
Definition at line 21 of file documentreader.cpp.
References _documentStack, _fileType, _includeSubDocuments, _indexFileInfo, _readElement(), _translationMapper, Settings::DEBUG, DocumentData::fileInfo(), Settings::getValue(), DocumentData::node(), and DocumentData::text().
Referenced by MainWindow::_open(), MainWindow::_performInitialOperations(), and Console::_performInitialOperations().
Member Data Documentation
QStack<DocumentData*> DocumentReader::_documentStack [private]
This stack is populated with DocumentData objects when processing the input document.
The usage of a stack allows to process the input document and its subdocuments in an iteration loop instead of a recursion because a recursion may raise a stack overflow issue.
Author:
Bjoern
Definition at line 65 of file documentreader.h.
Referenced by _readElement(), and read().
DocumentData::FileType DocumentReader::_fileType [private]
This attribute indicates of which type the input document is.
Author:
Bjoern
Definition at line 58 of file documentreader.h.
Referenced by _readElement(), DocumentReader(), and read().
bool DocumentReader::_includeSubDocuments [private]
This attribute indicates whether or not subdocuments are included by the input document processing.
Author:
Bjoern
Definition at line 70 of file documentreader.h.
Referenced by _readElement(), DocumentReader(), and read().
QFileInfo DocumentReader::_indexFileInfo [private]
This attribute provides detailed information about the input index file such as absolute and relative path etc.
Author:
Bjoern
Definition at line 54 of file documentreader.h.
Referenced by _readElement(), and read().
TranslationMapper* DocumentReader::_translationMapper [private]
The _translationMapper provides two data objects: firstly a DocumentReaderData object which is used by the DocumentReader and secondly a key-value-pair structure which is used by the Converter.
Author:
Bjoern
Definition at line 49 of file documentreader.h.
Referenced by _readElement(), DocumentReader(), and read().
The documentation for this class was generated from the following files:
documentreader.h
documentreader.cpp