htmLaTeX: CConverter Class Reference
CConverter Class Reference
This class converts the QDomDocument-Tree to a textfile by performing the conversions descibed in the 'Output-Definition'-XML file.
#include <cconverter.h>
Signals
void updateTextEdit (QString text)
void updateProgressBar (int percentage)
Public Member Functions
CConverter (QObject *parent, CTranslationMapper *translationmapper)
Constructor.
void convert (const QString filepath, CNode *root)
converts to QString and writes the output file
Private Types
enum DocumentPosition { start, content, end }
Private Member Functions
CNode * getLeaf (CNode *node=_cursor)
bool isLeaf (CNode *node=_cursor)
QMap< QString, QString > getAttributes (CNode *node=_cursor)
QString getContent (CNode *node=_cursor)
QString getName (CNode *node=_cursor)
bool consume (CNode *node=_cursor)
int match (QString content, QString pattern)
CNode * _getNextSibling ()
CNode * _getNextChild ()
CNode * _getNextNode ()
qint64 _getTreeLevel ()
QString _peekParent (qint32 distance)
QBool _isEmpty ()
QBool _isEmptyContent ()
void removeToken ()
void _consume ()
void _write (QString content, qint32 part)
qint64 _tryMatch (QString pattern)
QString _replace (CNode *node=_cursor)
Private Attributes
QFile _file
QTextStream _stream
CNode * _root
CTranslationMapper * _translationMapper
QString _errormessage
qint32 _noOfParts
QStringList replacementMarks
QStringList _parts
Static Private Attributes
static CNode * _cursor = 0
Detailed Description
This class converts the QDomDocument-Tree to a textfile by performing the conversions descibed in the 'Output-Definition'-XML file.
Author:
Bjoern Bass
Version:
0.1
Definition at line 22 of file cconverter.h.
Member Enumeration Documentation
enum CConverter::DocumentPosition [private]
Enumerator:
start
content
end
Definition at line 57 of file cconverter.h.
Constructor & Destructor Documentation
CConverter::CConverter (QObject * parent, CTranslationMapper * translationmapper)
Constructor.
Parameters:
<filepath> where to write the output
Parameters:
<root> the root-node of the QDomDocument to convert from TODO:
Parameters:
<parts> the number of parts that are needed for the conversion use enum{start=0, content=1, end=2} (change the XML aliases to numbers)
Definition at line 3 of file cconverter.cpp.
References _root, _translationMapper, and replacementMarks.
Member Function Documentation
void CConverter::_consume () [private]
CNode * CConverter::_getNextChild () [private]
Definition at line 130 of file cconverter.cpp.
References _cursor, and CNode::nextChild().
CNode * CConverter::_getNextNode () [private]
Definition at line 135 of file cconverter.cpp.
CNode * CConverter::_getNextSibling () [private]
Definition at line 118 of file cconverter.cpp.
References _cursor, CNode::childAt(), CNode::getCount(), CNode::getParent(), and CNode::indexOf().
qint64 CConverter::_getTreeLevel () [private]
Definition at line 142 of file cconverter.cpp.
References _root, and CNode::getTreeLevel().
QBool CConverter::_isEmpty () [private]
Definition at line 155 of file cconverter.cpp.
QBool CConverter::_isEmptyContent () [private]
Definition at line 160 of file cconverter.cpp.
References _cursor, and CNode::getContent().
QString CConverter::_peekParent (qint32 distance) [private]
Definition at line 148 of file cconverter.cpp.
QString CConverter::_replace (CNode * node = _cursor) [private]
Definition at line 176 of file cconverter.cpp.
References _translationMapper, CNode::getContent(), CNode::getName(), CTranslationMapper::outputMap(), replacementMarks, CTranslationData::requires(), and CTranslationData::to().
Referenced by consume().
qint64 CConverter::_tryMatch (QString pattern) [private]
Definition at line 171 of file cconverter.cpp.
void CConverter::_write (QString content, qint32 part) [private]
Definition at line 168 of file cconverter.cpp.
bool CConverter::consume (CNode * node = _cursor) [private]
Definition at line 86 of file cconverter.cpp.
References _cursor, _replace(), getLeaf(), CNode::getName(), CNode::getParent(), match(), CNode::removeChild(), replacementMarks, and CNode::setContent().
Referenced by convert().
void CConverter::convert (const QString filepath, CNode * root)
converts to QString and writes the output file
Parameters:
<qint32> the number of parts in the outputDocument
Definition at line 18 of file cconverter.cpp.
References _cursor, consume(), Settings::DEBUG, CNode::getContent(), CNode::getCount(), getLeaf(), CNode::getTreeNodeCount(), updateProgressBar(), and updateTextEdit().
Referenced by MainWindow::_convert(), MainWindow::_performInitialOperations(), and CConsole::_performInitialOperations().
QMap< QString, QString > CConverter::getAttributes (CNode * node = _cursor) [private]
Definition at line 74 of file cconverter.cpp.
References CNode::getAttributes().
QString CConverter::getContent (CNode * node = _cursor) [private]
Definition at line 78 of file cconverter.cpp.
References CNode::getContent().
CNode * CConverter::getLeaf (CNode * node = _cursor) [private]
Definition at line 63 of file cconverter.cpp.
References CNode::firstChild().
Referenced by consume(), and convert().
QString CConverter::getName (CNode * node = _cursor) [private]
bool CConverter::isLeaf (CNode * node = _cursor) [private]
Definition at line 70 of file cconverter.cpp.
References CNode::getCount().
int CConverter::match (QString content, QString pattern) [private]
Definition at line 195 of file cconverter.cpp.
Referenced by consume().
void CConverter::removeToken () [private]
Definition at line 165 of file cconverter.cpp.
void CConverter::updateProgressBar (int percentage) [signal]
Referenced by convert().
void CConverter::updateTextEdit (QString text) [signal]
Referenced by convert().
Member Data Documentation
CNode * CConverter::_cursor = 0 [static, private]
Definition at line 51 of file cconverter.h.
Referenced by _getNextChild(), _getNextSibling(), _isEmptyContent(), consume(), and convert().
QString CConverter::_errormessage [private]
Definition at line 52 of file cconverter.h.
QFile CConverter::_file [private]
Definition at line 44 of file cconverter.h.
qint32 CConverter::_noOfParts [private]
Definition at line 53 of file cconverter.h.
QStringList CConverter::_parts [private]
Definition at line 61 of file cconverter.h.
CNode* CConverter::_root [private]
Definition at line 48 of file cconverter.h.
Referenced by _getTreeLevel(), and CConverter().
QTextStream CConverter::_stream [private]
Definition at line 46 of file cconverter.h.
CTranslationMapper* CConverter::_translationMapper [private]
Definition at line 49 of file cconverter.h.
Referenced by _replace(), and CConverter().
QStringList CConverter::replacementMarks [private]
Definition at line 54 of file cconverter.h.
Referenced by _replace(), CConverter(), and consume().
The documentation for this class was generated from the following files:
/home/bjoern/projekt/htmlatex/cconverter.h
/home/bjoern/projekt/htmlatex/cconverter.cpp