htmLaTeX: CModel Class Reference
CModel Class Reference
#include <cmodel.h>
Public Member Functions
CNode * nodeFromIndex (const QModelIndex &index) const
void setRootNode (CNode *node)
CNode * root () const
QModelIndex index (int row, int column, const QModelIndex &parent) const
QModelIndex parent (const QModelIndex &child) const
int rowCount (const QModelIndex &parent) const
int columnCount (const QModelIndex &parent) const
QVariant data (const QModelIndex &index, int role) const
QVariant headerData (int section, Qt::Orientation orientation, int role) const
void refresh ()
CModel (QObject *parent=0)
~CModel ()
Private Attributes
CNode * _root
Detailed Description
Definition at line 7 of file cmodel.h.
Constructor & Destructor Documentation
CModel::CModel (QObject * parent = 0)
Definition at line 3 of file cmodel.cpp.
CModel::~CModel ()
Definition at line 6 of file cmodel.cpp.
References _root.
Member Function Documentation
int CModel::columnCount (const QModelIndex & parent) const
Definition at line 46 of file cmodel.cpp.
QVariant CModel::data (const QModelIndex & index, int role) const
Definition at line 65 of file cmodel.cpp.
References CNode::getContent(), CNode::getName(), and nodeFromIndex().
QVariant CModel::headerData (int section, Qt::Orientation orientation, int role) const
Definition at line 74 of file cmodel.cpp.
QModelIndex CModel::index (int row, int column, const QModelIndex & parent) const
Definition at line 17 of file cmodel.cpp.
References _root, CNode::childAt(), and nodeFromIndex().
CNode * CModel::nodeFromIndex (const QModelIndex & index) const
Definition at line 29 of file cmodel.cpp.
References _root.
Referenced by MainWindow::_showTreeViewContextMenu(), MainWindow::_treeViewRemoveNode(), data(), index(), CItemDelegate::paint(), parent(), and rowCount().
QModelIndex CModel::parent (const QModelIndex & child) const
Definition at line 51 of file cmodel.cpp.
References CNode::getParent(), CNode::indexOf(), and nodeFromIndex().
void CModel::refresh ()
Definition at line 82 of file cmodel.cpp.
Referenced by MainWindow::_treeViewRemoveNode().
CNode * CModel::root () const
Definition at line 78 of file cmodel.cpp.
References _root.
Referenced by MainWindow::_convert(), and MainWindow::_performInitialOperations().
int CModel::rowCount (const QModelIndex & parent) const
Definition at line 37 of file cmodel.cpp.
References CNode::getCount(), and nodeFromIndex().
void CModel::setRootNode (CNode * node)
Definition at line 10 of file cmodel.cpp.
References _root.
Referenced by MainWindow::_open(), and MainWindow::_performInitialOperations().
Member Data Documentation
CNode* CModel::_root [private]
Definition at line 10 of file cmodel.h.
Referenced by index(), nodeFromIndex(), root(), setRootNode(), and ~CModel().
The documentation for this class was generated from the following files:
/home/bjoern/projekt/htmlatex/cmodel.h
/home/bjoern/projekt/htmlatex/cmodel.cpp