htmLaTeX: CDocumentData Class Reference
CDocumentData Class Reference
#include <cdocumentdata.h>
Public Types
enum FileType { JavaDocHTML, HTML, Tex, Unknown }
Public Member Functions
QFileInfo fileInfo () const
Returns the URL to this document.
CNode * node () const
Returns the pointer to the corresponding tree node of the whole document.
QString text ()
Returns the document as a preprocessed QString.
FileType fileType () const
QFileInfo indexFileInfo () const
CDocumentData (QFileInfo fileinfo, CNode *node, FileType filetype)
This class holds information of one document (i.e.
Private Member Functions
void preprocessingHook ()
This hook-method calls all preprocessing methods.
void preprocessHTML ()
This method changes the specified HTML-file in order to gain well-formed XML (XHTML).
bool isPreprocessed () const
Private Attributes
QFileInfo _fileInfo
CNode * _node
QString _text
FileType _fileType
bool _preprocessed
Detailed Description
Definition at line 14 of file cdocumentdata.h.
Member Enumeration Documentation
enum CDocumentData::FileType
Enumerator:
JavaDocHTML
HTML
Tex
Unknown
Definition at line 17 of file cdocumentdata.h.
Constructor & Destructor Documentation
CDocumentData::CDocumentData (QFileInfo fileinfo, CNode * node, FileType filetype)
This class holds information of one document (i.e.
webpage). The information consists of the file path (URL), a reference pointing to the corresponding node in the document tree, which represents the whole document. This also stores a QFileInfo-object for the whole documents' index document. The appropriate document preprocessing is chosen by means of distinguished file types.
Author:
Bjoern Kaiser
Definition at line 10 of file cdocumentdata.cpp.
References _fileInfo, _fileType, _node, _preprocessed, and _text.
Member Function Documentation
QFileInfo CDocumentData::fileInfo () const
Returns the URL to this document.
Author:
Bjoern Kaiser
Definition at line 21 of file cdocumentdata.cpp.
References _fileInfo.
Referenced by CDocumentReader::read().
FileType CDocumentData::fileType () const
QFileInfo CDocumentData::indexFileInfo () const
bool CDocumentData::isPreprocessed () const [private]
CNode * CDocumentData::node () const
Returns the pointer to the corresponding tree node of the whole document.
Author:
Bjoern Kaiser
Definition at line 28 of file cdocumentdata.cpp.
References _node.
Referenced by CDocumentReader::read().
void CDocumentData::preprocessHTML () [private]
This method changes the specified HTML-file in order to gain well-formed XML (XHTML).
Author:
Bjoern Kaiser
Definition at line 52 of file cdocumentdata.cpp.
References _fileInfo, _fileType, _preprocessed, _text, Settings::DEBUG, and JavaDocHTML.
Referenced by preprocessingHook().
void CDocumentData::preprocessingHook () [private]
This hook-method calls all preprocessing methods.
Author:
Bjoern Kaiser
Definition at line 45 of file cdocumentdata.cpp.
References preprocessHTML().
Referenced by text().
QString CDocumentData::text ()
Returns the document as a preprocessed QString.
Author:
Bjoern Kaiser
Definition at line 35 of file cdocumentdata.cpp.
References _preprocessed, _text, and preprocessingHook().
Referenced by CDocumentReader::read().
Member Data Documentation
QFileInfo CDocumentData::_fileInfo [private]
Definition at line 19 of file cdocumentdata.h.
Referenced by CDocumentData(), fileInfo(), and preprocessHTML().
FileType CDocumentData::_fileType [private]
Definition at line 22 of file cdocumentdata.h.
Referenced by CDocumentData(), and preprocessHTML().
CNode* CDocumentData::_node [private]
Definition at line 20 of file cdocumentdata.h.
Referenced by CDocumentData(), and node().
bool CDocumentData::_preprocessed [private]
Definition at line 23 of file cdocumentdata.h.
Referenced by CDocumentData(), preprocessHTML(), and text().
QString CDocumentData::_text [private]
Definition at line 21 of file cdocumentdata.h.
Referenced by CDocumentData(), preprocessHTML(), and text().
The documentation for this class was generated from the following files:
/home/bjoern/projekt/htmlatex/cdocumentdata.h
/home/bjoern/projekt/htmlatex/cdocumentdata.cpp