htmLaTeX: CDocumentReader Class Reference
CDocumentReader Class Reference
#include <cdocumentreader.h>
Public Member Functions
CNode * read (QString indexfilepath, CDocumentData::FileType filetype)
This method.
void setTranslationMapper (CTranslationMapper *translationmapper)
CDocumentReader ()
This class creates a tree representation of a given document.
Private Member Functions
void readElement (QDomElement element, CNode *node)
Private Attributes
QFileInfo _indexFileInfo
CDocumentData::FileType _fileType
QStack< CDocumentData * > _documentStack
CTranslationMapper * _translationMapper
Detailed Description
Definition at line 17 of file cdocumentreader.h.
Constructor & Destructor Documentation
CDocumentReader::CDocumentReader ()
This class creates a tree representation of a given document.
Author:
Bjoern Kaiser
Definition at line 6 of file cdocumentreader.cpp.
References _fileType, and CDocumentData::Unknown.
Member Function Documentation
CNode * CDocumentReader::read (QString indexfilepath, CDocumentData::FileType filetype)
This method.
Parameters:
filetype contains the file filter string selected previously.
Author:
Bjoern Kaiser
Definition at line 14 of file cdocumentreader.cpp.
References _documentStack, _fileType, _indexFileInfo, CDocumentData::fileInfo(), CDocumentData::node(), readElement(), and CDocumentData::text().
Referenced by MainWindow::_open(), MainWindow::_performInitialOperations(), and CConsole::_performInitialOperations().
void CDocumentReader::readElement (QDomElement element, CNode * node) [private]
Definition at line 65 of file cdocumentreader.cpp.
References _documentStack, _fileType, _indexFileInfo, CNode::addAttribute(), CNode::addChild(), Settings::DEBUG, CNode::getAttributes(), CNode::getLayer(), and CNode::setContent().
Referenced by read().
void CDocumentReader::setTranslationMapper (CTranslationMapper * translationmapper)
Definition at line 128 of file cdocumentreader.cpp.
References _translationMapper.
Referenced by MainWindow::_open(), and MainWindow::_performInitialOperations().
Member Data Documentation
QStack<CDocumentData*> CDocumentReader::_documentStack [private]
Definition at line 22 of file cdocumentreader.h.
Referenced by read(), and readElement().
CDocumentData::FileType CDocumentReader::_fileType [private]
Definition at line 21 of file cdocumentreader.h.
Referenced by CDocumentReader(), read(), and readElement().
QFileInfo CDocumentReader::_indexFileInfo [private]
Definition at line 20 of file cdocumentreader.h.
Referenced by read(), and readElement().
CTranslationMapper* CDocumentReader::_translationMapper [private]
Definition at line 23 of file cdocumentreader.h.
Referenced by setTranslationMapper().
The documentation for this class was generated from the following files:
/home/bjoern/projekt/htmlatex/cdocumentreader.h
/home/bjoern/projekt/htmlatex/cdocumentreader.cpp