htmLaTeX: CNode Class Reference
CNode Class Reference
The CNode class provides rudimental functionality to build tree structures and access its nodes.
#include <cnode.h>
Public Member Functions
CNode (const CNode &node)
This is the copy-constructor of the class.
CNode (CNode *parent, QString name, qint64 layer)
This constructor creates an instance initiallzing its _parent, _name and and _layer number.
~CNode ()
This destructor ensures that all child nodes are deleted as well.
qint64 getTreeLevel () const
This method returns the _treeLevel number (class member).
qint64 getTreeNodeCount () const
This method returns the number of nodes of the whole tree (class member).
qint64 getID () const
This method returns the ID of the node.
qint64 getLayer () const
This method returns the _layer number of the node.
QString getName () const
This method returns the name of the node.
void setName (QString name)
This method sets the name of the node.
QString getContent () const
This method returns the content of the node.
void setContent (QString content)
This method sets the content of the node.
CNode * getParent () const
This method returns a pointer pointing to the parent node object.
void setParent (CNode *parent)
This method sets the pointer pointing to the parent node object.
int getCount () const
This method returns the number of child nodes.
bool containsChild (CNode *node) const
This method returns true, if the array of child nodes (_children) contains the specified pointer to a CNode object.
CNode * childAt (int index) const
This method returns a pointer to the child node specified by its array index.
CNode * nextChild ()
This method returns a pointer to the next child node by moving the _cursor one step forward (increment of 1).
CNode * firstChild ()
This method returns a pointer to the first child node.
CNode * lastChild ()
This method returns a pointer to the last child node.
void addChildren (QList< CNode * > nodes)
This method appends a generic array of pointers pointing to CNode objects to the array of child nodes (_children).
void addChild (CNode *node)
This method appends a pointer pointing to a CNode object to the array of child nodes (_children).
void removeChild (CNode *node)
This method removes the specified pointer pointing to a CNode object from the array of child nodes (_chidren).
int indexOf (CNode *node) const
This method returns the array index of the specified pointer pointing to a CNode object.
QMap< QString, QString > getAttributes () const
This method returns the attributes of the node.
void addAttribute (QString key, QString value)
This method adds an attribute by means of a key-value-pair.
Private Attributes
qint64 _id
The _id is a unique number which allows identification of the node.
qint64 _layer
The _layer numbers allows to determine to which layer / generation a node belongs.
QString _name
This is the name of the node.
QString _content
This is the content of the node.
CNode * _parent
This pointer points to the parent node.
QList< CNode * > _children
This is generic array of pointers pointing to the child nodes.
QMap< QString, QString > _attributes
This is a key-value-structure which provides access to the value of type QString via keys of the type QString.
int _cursor
The _cursor indicates the current index position within the array of child nodes (_children).
Static Private Attributes
static qint64 _instCount = 0
The _instCount class member counts the created instances of the CNode class.
static qint64 _treeLevel = 0
The _treeLevel attribute holds the greatest distance of a leaf to the root of the whole tree.
static qint64 _treeNodeCount
The _treeNodeCount attribute holds the number of nodes of the whole tree.
Detailed Description
The CNode class provides rudimental functionality to build tree structures and access its nodes.
Each node is aware of its parent and children which can be accessed by methods such as getParent() or childAt(). Additionally each node holds an array of attributes.
Definition at line 13 of file cnode.h.
Constructor & Destructor Documentation
CNode::CNode (const CNode & node)
This is the copy-constructor of the class.
Definition at line 3 of file cnode.cpp.
References _content, _id, _instCount, _layer, _name, _parent, _treeLevel, addAttribute(), addChild(), childAt(), getAttributes(), getContent(), getCount(), getLayer(), getName(), getParent(), and getTreeLevel().
CNode::CNode (CNode * parent, QString name, qint64 layer)
This constructor creates an instance initiallzing its _parent, _name and and _layer number.
Definition at line 20 of file cnode.cpp.
References _attributes, _children, _id, _instCount, _parent, _treeLevel, and _treeNodeCount.
CNode::~CNode ()
This destructor ensures that all child nodes are deleted as well.
Definition at line 34 of file cnode.cpp.
References _children.
Member Function Documentation
void CNode::addAttribute (QString key, QString value)
This method adds an attribute by means of a key-value-pair.
Definition at line 167 of file cnode.cpp.
References _attributes.
Referenced by CNode(), and DocumentReader::readElement().
void CNode::addChild (CNode * node)
This method appends a pointer pointing to a CNode object to the array of child nodes (_children).
Definition at line 140 of file cnode.cpp.
References _children, containsChild(), and setParent().
Referenced by CNode(), and DocumentReader::readElement().
void CNode::addChildren (QList< CNode * > nodes)
This method appends a generic array of pointers pointing to CNode objects to the array of child nodes (_children).
Definition at line 129 of file cnode.cpp.
References _children, and containsChild().
CNode * CNode::childAt (int index) const
This method returns a pointer to the child node specified by its array index.
Definition at line 100 of file cnode.cpp.
References _children.
Referenced by Converter::_getNextSibling(), CNode(), and Model::index().
bool CNode::containsChild (CNode * node) const
This method returns true, if the array of child nodes (_children) contains the specified pointer to a CNode object.
Definition at line 87 of file cnode.cpp.
References _children, and _id.
Referenced by addChild(), and addChildren().
CNode * CNode::firstChild ()
This method returns a pointer to the first child node.
If the node has no children null is returned.
Definition at line 113 of file cnode.cpp.
References _children, and _cursor.
Referenced by Converter::getLeaf().
QMap< QString, QString > CNode::getAttributes () const
This method returns the attributes of the node.
Definition at line 163 of file cnode.cpp.
References _attributes.
Referenced by CNode(), Converter::getAttributes(), and DocumentReader::readElement().
QString CNode::getContent () const
This method returns the content of the node.
Definition at line 65 of file cnode.cpp.
References _content.
Referenced by Converter::_isEmptyContent(), Converter::_replace(), CNode(), Converter::convert(), Model::data(), Converter::getContent(), and ItemDelegate::paint().
int CNode::getCount () const
This method returns the number of child nodes.
Definition at line 83 of file cnode.cpp.
References _children.
Referenced by Converter::_getNextSibling(), MainWindow::_performInitialOperations(), CNode(), Converter::convert(), Converter::isLeaf(), and Model::rowCount().
qint64 CNode::getID () const
This method returns the ID of the node.
Definition at line 49 of file cnode.cpp.
References _id.
qint64 CNode::getLayer () const
This method returns the _layer number of the node.
Definition at line 53 of file cnode.cpp.
References _layer.
Referenced by MainWindow::_treeViewRemoveNode(), CNode(), ItemDelegate::paint(), and DocumentReader::readElement().
QString CNode::getName () const
This method returns the name of the node.
Definition at line 57 of file cnode.cpp.
References _name.
Referenced by Converter::_replace(), CNode(), Model::data(), Converter::getName(), and ItemDelegate::paint().
CNode * CNode::getParent () const
This method returns a pointer pointing to the parent node object.
Definition at line 73 of file cnode.cpp.
References _parent.
Referenced by Converter::_getNextSibling(), MainWindow::_treeViewRemoveNode(), CNode(), Converter::consume(), and Model::parent().
qint64 CNode::getTreeLevel () const
This method returns the _treeLevel number (class member).
Definition at line 41 of file cnode.cpp.
References _treeLevel.
Referenced by Converter::_getTreeLevel(), and CNode().
qint64 CNode::getTreeNodeCount () const
This method returns the number of nodes of the whole tree (class member).
Definition at line 45 of file cnode.cpp.
References _treeNodeCount.
Referenced by Converter::convert().
int CNode::indexOf (CNode * node) const
This method returns the array index of the specified pointer pointing to a CNode object.
If it isn't contained in the array of child dnodes -1 is returned.
Definition at line 159 of file cnode.cpp.
References _children.
Referenced by Converter::_getNextSibling(), and Model::parent().
CNode * CNode::lastChild ()
This method returns a pointer to the last child node.
If the node has no children null is returned.
Definition at line 120 of file cnode.cpp.
References _children, and _cursor.
CNode * CNode::nextChild ()
This method returns a pointer to the next child node by moving the _cursor one step forward (increment of 1).
If the node has less than two children null is returned.
Definition at line 104 of file cnode.cpp.
References _children, and _cursor.
Referenced by Converter::_getNextChild().
void CNode::removeChild (CNode * node)
This method removes the specified pointer pointing to a CNode object from the array of child nodes (_chidren).
Definition at line 151 of file cnode.cpp.
References _children, and _cursor.
Referenced by MainWindow::_treeViewRemoveNode(), and Converter::consume().
void CNode::setContent (QString content)
This method sets the content of the node.
Definition at line 69 of file cnode.cpp.
References _content.
Referenced by Converter::consume(), and DocumentReader::readElement().
void CNode::setName (QString name)
This method sets the name of the node.
Definition at line 61 of file cnode.cpp.
References _name.
void CNode::setParent (CNode * parent)
This method sets the pointer pointing to the parent node object.
Definition at line 79 of file cnode.cpp.
References _parent.
Referenced by addChild().
Member Data Documentation
QMap<QString, QString> CNode::_attributes [private]
This is a key-value-structure which provides access to the value of type QString via keys of the type QString.
Definition at line 39 of file cnode.h.
Referenced by addAttribute(), CNode(), and getAttributes().
QList<CNode*> CNode::_children [private]
This is generic array of pointers pointing to the child nodes.
Definition at line 36 of file cnode.h.
Referenced by addChild(), addChildren(), childAt(), CNode(), containsChild(), firstChild(), getCount(), indexOf(), lastChild(), nextChild(), removeChild(), and ~CNode().
QString CNode::_content [private]
This is the content of the node.
Definition at line 32 of file cnode.h.
Referenced by CNode(), getContent(), and setContent().
int CNode::_cursor [private]
The _cursor indicates the current index position within the array of child nodes (_children).
The _cursor moves when the methods firstChild(), nextChild() and lastChild() are called.
Definition at line 43 of file cnode.h.
Referenced by firstChild(), lastChild(), nextChild(), and removeChild().
qint64 CNode::_id [private]
The _id is a unique number which allows identification of the node.
Definition at line 24 of file cnode.h.
Referenced by CNode(), containsChild(), and getID().
qint64 CNode::_instCount = 0 [static, private]
The _instCount class member counts the created instances of the CNode class.
Definition at line 17 of file cnode.h.
Referenced by CNode().
qint64 CNode::_layer [private]
The _layer numbers allows to determine to which layer / generation a node belongs.
The root node has the _layer number 0, its children 1 and its grand children 2 and so on.
Definition at line 28 of file cnode.h.
Referenced by CNode(), and getLayer().
QString CNode::_name [private]
This is the name of the node.
Definition at line 30 of file cnode.h.
Referenced by CNode(), getName(), and setName().
CNode* CNode::_parent [private]
This pointer points to the parent node.
In case of the root node it points to null.
Definition at line 34 of file cnode.h.
Referenced by CNode(), getParent(), and setParent().
qint64 CNode::_treeLevel = 0 [static, private]
The _treeLevel attribute holds the greatest distance of a leaf to the root of the whole tree.
Definition at line 20 of file cnode.h.
Referenced by CNode(), and getTreeLevel().
qint64 CNode::_treeNodeCount [static, private]
The _treeNodeCount attribute holds the number of nodes of the whole tree.
Definition at line 22 of file cnode.h.
Referenced by CNode(), and getTreeNodeCount().
The documentation for this class was generated from the following files:
cnode.h
cnode.cpp