htmLaTeX: /home/bjoern/projekt/htmlatex/qrc_resource.cpp File Reference
/home/bjoern/projekt/htmlatex/qrc_resource.cpp File Reference
#include <QtCore/qglobal.h>
Functions
QT_BEGIN_NAMESPACE
Q_CORE_EXPORT bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
Q_CORE_EXPORT bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
QT_END_NAMESPACE int
QT_MANGLE_NAMESPACE() qInitResources_resource ()
int QT_MANGLE_NAMESPACE() qCleanupResources_resource ()
Variables
static const unsigned char qt_resource_data []
static const unsigned char qt_resource_name []
static const unsigned char qt_resource_struct []
Function Documentation
int QT_MANGLE_NAMESPACE() qCleanupResources_resource ()
Definition at line 28608 of file qrc_resource.cpp.
References qt_resource_data, qt_resource_name, qt_resource_struct, and qUnregisterResourceData().
QT_END_NAMESPACE int QT_MANGLE_NAMESPACE() qInitResources_resource ()
Definition at line 28599 of file qrc_resource.cpp.
References qRegisterResourceData(), qt_resource_data, qt_resource_name, and qt_resource_struct.
QT_BEGIN_NAMESPACE Q_CORE_EXPORT bool qRegisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qInitResources_resource().
Q_CORE_EXPORT bool qUnregisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qCleanupResources_resource().
Variable Documentation
const unsigned char qt_resource_data[] [static]
Definition at line 12 of file qrc_resource.cpp.
Referenced by qCleanupResources_resource(), and qInitResources_resource().
const unsigned char qt_resource_name[] [static]
Definition at line 26965 of file qrc_resource.cpp.
Referenced by qCleanupResources_resource(), and qInitResources_resource().
const unsigned char qt_resource_struct[] [static]
Definition at line 28136 of file qrc_resource.cpp.
Referenced by qCleanupResources_resource(), and qInitResources_resource().