htmLaTeX: CTranslationData Class Reference
CTranslationData Class Reference
#include <ctranslationdata.h>
Public Member Functions
QString key () const
void setKey (QString key)
QString from () const
void setFrom (QString from)
QString to () const
void setTo (QString to)
QList< CTranslationDataNode > requires () const
void addRequiresNode (CTranslationDataNode requiresnode)
CTranslationData ()
Private Attributes
QString _key
QString _from
QString _to
QList< CTranslationDataNode > _requires
Detailed Description
Definition at line 8 of file ctranslationdata.h.
Constructor & Destructor Documentation
CTranslationData::CTranslationData ()
Definition at line 3 of file ctranslationdata.cpp.
References _requires.
Member Function Documentation
void CTranslationData::addRequiresNode (CTranslationDataNode requiresnode)
Definition at line 35 of file ctranslationdata.cpp.
References _requires.
Referenced by CTranslationMapper::createOutputElementMap().
QString CTranslationData::from () const
Definition at line 7 of file ctranslationdata.cpp.
References _from.
QString CTranslationData::key () const
Definition at line 15 of file ctranslationdata.cpp.
References _key.
Referenced by CTranslationMapper::createOutputElementMap().
QList< CTranslationDataNode > CTranslationData::requires () const
Definition at line 31 of file ctranslationdata.cpp.
References _requires.
Referenced by CConverter::_replace().
void CTranslationData::setFrom (QString from)
Definition at line 11 of file ctranslationdata.cpp.
References _from.
Referenced by CTranslationMapper::createOutputElementMap().
void CTranslationData::setKey (QString key)
Definition at line 19 of file ctranslationdata.cpp.
References _key.
Referenced by CTranslationMapper::createOutputElementMap().
void CTranslationData::setTo (QString to)
Definition at line 27 of file ctranslationdata.cpp.
References _to.
Referenced by CTranslationMapper::createOutputElementMap().
QString CTranslationData::to () const
Definition at line 23 of file ctranslationdata.cpp.
References _to.
Referenced by CConverter::_replace().
Member Data Documentation
QString CTranslationData::_from [private]
Definition at line 13 of file ctranslationdata.h.
Referenced by from(), and setFrom().
QString CTranslationData::_key [private]
Definition at line 12 of file ctranslationdata.h.
Referenced by key(), and setKey().
QList<CTranslationDataNode> CTranslationData::_requires [private]
Definition at line 15 of file ctranslationdata.h.
Referenced by addRequiresNode(), CTranslationData(), and requires().
QString CTranslationData::_to [private]
Definition at line 14 of file ctranslationdata.h.
Referenced by setTo(), and to().
The documentation for this class was generated from the following files:
/home/bjoern/projekt/htmlatex/ctranslationdata.h
/home/bjoern/projekt/htmlatex/ctranslationdata.cpp