htmLaTeX: Model Class Reference
Model Class Reference
#include <model.h>
Public Member Functions
Node * nodeFromIndex (const QModelIndex &index) const
void setRootNode (Node *node)
Node * root () const
QModelIndex index (int row, int column, const QModelIndex &parent) const
QModelIndex parent (const QModelIndex &child) const
int rowCount (const QModelIndex &parent) const
int columnCount (const QModelIndex &parent) const
QVariant data (const QModelIndex &index, int role) const
QVariant headerData (int section, Qt::Orientation orientation, int role) const
void refresh ()
Model (QObject *parent=0)
Constructor.
~Model ()
Private Attributes
Node * _root
Detailed Description
Definition at line 7 of file model.h.
Constructor & Destructor Documentation
Model::Model (QObject * parent = 0)
Constructor.
Definition at line 3 of file model.cpp.
Model::~Model ()
Definition at line 6 of file model.cpp.
References _root.
Member Function Documentation
int Model::columnCount (const QModelIndex & parent) const
Definition at line 46 of file model.cpp.
QVariant Model::data (const QModelIndex & index, int role) const
Definition at line 65 of file model.cpp.
References Node::getContent(), Node::getName(), and nodeFromIndex().
QVariant Model::headerData (int section, Qt::Orientation orientation, int role) const
Definition at line 74 of file model.cpp.
QModelIndex Model::index (int row, int column, const QModelIndex & parent) const
Definition at line 17 of file model.cpp.
References _root, Node::childAt(), and nodeFromIndex().
Node * Model::nodeFromIndex (const QModelIndex & index) const
Definition at line 29 of file model.cpp.
References _root.
Referenced by MainWindow::_showTreeViewContextMenu(), MainWindow::_treeViewRemoveNode(), data(), index(), ItemDelegate::paint(), parent(), and rowCount().
QModelIndex Model::parent (const QModelIndex & child) const
Definition at line 51 of file model.cpp.
References Node::getParent(), Node::indexOf(), and nodeFromIndex().
void Model::refresh ()
Definition at line 82 of file model.cpp.
Referenced by MainWindow::_treeViewRemoveNode().
Node * Model::root () const
Definition at line 78 of file model.cpp.
References _root.
Referenced by MainWindow::_convert(), and MainWindow::_performInitialOperations().
int Model::rowCount (const QModelIndex & parent) const
Definition at line 37 of file model.cpp.
References Node::getCount(), and nodeFromIndex().
void Model::setRootNode (Node * node)
Definition at line 10 of file model.cpp.
References _root.
Referenced by MainWindow::_open(), and MainWindow::_performInitialOperations().
Member Data Documentation
Node* Model::_root [private]
Definition at line 10 of file model.h.
Referenced by index(), nodeFromIndex(), root(), setRootNode(), and ~Model().
The documentation for this class was generated from the following files:
model.h
model.cpp