htmLaTeX: Node Class Reference
Node Class Reference
The Node class provides rudimental functionality to build tree structures and access its nodes.
#include <node.h>
Public Member Functions
Node (const Node &node)
This is the copy-construcotr of the class.
Node (Node *parent, QString name, qint64 layer)
This constructor creates an instance initiallzing its _parent, _name and and _layer number.
~Node ()
This destructor ensures that all child nodes are deleted as well.
qint64 getTreeLevel () const
This method returns the _treeLevel number (class member).
qint64 getTreeNodeCount () const
This method returns the number of nodes of the whole tree (class member).
qint64 getID () const
This method returns the ID of the node.
qint64 getLayer () const
This method returns the _layer number of the node.
QString getName () const
This method returns the name of the node.
void setName (QString name)
This method sets the name of the node.
QString getContent () const
This method returns the content of the node.
void setContent (QString content)
This method sets the content of the node.
Node * getParent () const
This method returns a pointer pointing to the parent node object.
void setParent (Node *parent)
This method sets the pointer pointing to the parent node object.
int getCount () const
This method returns the number of child nodes.
bool containsChild (Node *node) const
This method returns true, if the array of child nodes (_children) contains the specified pointer to a Node object.
Node * childAt (int index) const
This method returns a pointer to the child node specified by its array index.
Node * nextChild ()
This method returns a pointer to the next child node by moving the _cursor one step forward (increment of 1).
Node * firstChild ()
This method returns a pointer to the first child node.
Node * lastChild ()
This method returns a pointer to the last child node.
void addChildren (QList< Node * > nodes)
This method appends a generic array of pointers pointing to Node objects to the array of child nodes (_children).
void addChild (Node *node)
This method appends a pointer pointing to a Node object to the array of child nodes (_children).
void removeChild (Node *node)
This method removes the specified pointer pointing to a Node object from the array of child nodes (_chidren).
int indexOf (Node *node) const
This method returns the array index of the specified pointer pointing to a Node object.
QMap< QString, QString > getAttributes () const
This method returns the attributes of the node.
void addAttribute (QString key, QString value)
This method adds an attribute by means of a key-value-pair.
Private Attributes
qint64 _id
The _id is a unique number which allows identification of the node.
qint64 _layer
The _layer numbers allows to determine to which layer / generation a node belongs.
QString _name
This is the name of the node.
QString _content
This is the content of the node.
Node * _parent
This pointer points to the parent node.
QList< Node * > _children
This is generic array of pointers pointing to the child nodes.
QMap< QString, QString > _attributes
This is a key-value-structure which provides access to the value of type QString via keys of the type QString.
int _cursor
The _cursor indicates the current index position within the array of child nodes (_children).
Static Private Attributes
static qint64 _instCount = 0
The _instCount class member counts the created instances of the Node class.
static qint64 _treeLevel = 0
The _treeLevel attribute holds the greatest distance of a leaf to the root of the whole tree.
static qint64 _treeNodeCount
The _treeNodeCount attribute holds the number of nodes of the whole tree.
Detailed Description
The Node class provides rudimental functionality to build tree structures and access its nodes.
Each node is aware of its parent and children which can be accessed by methods such as getParent() or childAt(int index). Additionally each node holds an array of attributes.
Definition at line 13 of file node.h.
Constructor & Destructor Documentation
Node::Node (const Node & node)
This is the copy-construcotr of the class.
Author:
Bjoern
Definition at line 3 of file node.cpp.
References _content, _id, _instCount, _layer, _name, _parent, _treeLevel, addAttribute(), addChild(), childAt(), getAttributes(), getContent(), getCount(), getLayer(), getName(), getParent(), and getTreeLevel().
Node::Node (Node * parent, QString name, qint64 layer)
This constructor creates an instance initiallzing its _parent, _name and and _layer number.
Author:
Bjoern
Definition at line 20 of file node.cpp.
References _attributes, _children, _id, _instCount, _parent, _treeLevel, and _treeNodeCount.
Node::~Node ()
This destructor ensures that all child nodes are deleted as well.
Author:
Bjoern
Definition at line 34 of file node.cpp.
References _children.
Member Function Documentation
void Node::addAttribute (QString key, QString value)
This method adds an attribute by means of a key-value-pair.
Author:
Bjoern
Definition at line 167 of file node.cpp.
References _attributes.
Referenced by Node(), and DocumentReader::readElement().
void Node::addChild (Node * node)
This method appends a pointer pointing to a Node object to the array of child nodes (_children).
Author:
Bjoern
Definition at line 140 of file node.cpp.
References _children, containsChild(), and setParent().
Referenced by Node(), and DocumentReader::readElement().
void Node::addChildren (QList< Node * > nodes)
This method appends a generic array of pointers pointing to Node objects to the array of child nodes (_children).
Author:
Bjoern
Definition at line 129 of file node.cpp.
References _children, and containsChild().
Node * Node::childAt (int index) const
This method returns a pointer to the child node specified by its array index.
Author:
Bjoern
Definition at line 100 of file node.cpp.
References _children.
Referenced by Converter::_getNextSibling(), Model::index(), and Node().
bool Node::containsChild (Node * node) const
This method returns true, if the array of child nodes (_children) contains the specified pointer to a Node object.
Author:
Bjoern
Definition at line 87 of file node.cpp.
References _children, and _id.
Referenced by addChild(), and addChildren().
Node * Node::firstChild ()
This method returns a pointer to the first child node.
If the node has no children null is returned.
Author:
Bjoern
Definition at line 113 of file node.cpp.
References _children, and _cursor.
Referenced by Converter::getLeaf().
QMap< QString, QString > Node::getAttributes () const
This method returns the attributes of the node.
Author:
Bjoern
Definition at line 163 of file node.cpp.
References _attributes.
Referenced by Converter::getAttributes(), Node(), and DocumentReader::readElement().
QString Node::getContent () const
This method returns the content of the node.
Author:
Bjoern
Definition at line 65 of file node.cpp.
References _content.
Referenced by Converter::_isEmptyContent(), Converter::_replace(), Converter::convert(), Model::data(), Converter::getContent(), Node(), and ItemDelegate::paint().
int Node::getCount () const
This method returns the number of child nodes.
Author:
Bjoern
Definition at line 83 of file node.cpp.
References _children.
Referenced by Converter::_getNextSibling(), MainWindow::_performInitialOperations(), Converter::convert(), Converter::isLeaf(), Node(), and Model::rowCount().
qint64 Node::getID () const
This method returns the ID of the node.
Author:
Bjoern
Definition at line 49 of file node.cpp.
References _id.
qint64 Node::getLayer () const
This method returns the _layer number of the node.
Author:
Bjoern
Definition at line 53 of file node.cpp.
References _layer.
Referenced by MainWindow::_treeViewRemoveNode(), Node(), ItemDelegate::paint(), and DocumentReader::readElement().
QString Node::getName () const
This method returns the name of the node.
Author:
Bjoern
Definition at line 57 of file node.cpp.
References _name.
Referenced by Converter::_replace(), Model::data(), Converter::getName(), Node(), and ItemDelegate::paint().
Node * Node::getParent () const
This method returns a pointer pointing to the parent node object.
Author:
Bjoern
Definition at line 73 of file node.cpp.
References _parent.
Referenced by Converter::_getNextSibling(), MainWindow::_treeViewRemoveNode(), Converter::consume(), Node(), and Model::parent().
qint64 Node::getTreeLevel () const
This method returns the _treeLevel number (class member).
Author:
Bjoern
Definition at line 41 of file node.cpp.
References _treeLevel.
Referenced by Converter::_getTreeLevel(), and Node().
qint64 Node::getTreeNodeCount () const
This method returns the number of nodes of the whole tree (class member).
Author:
Bjoern
Definition at line 45 of file node.cpp.
References _treeNodeCount.
Referenced by Converter::convert().
int Node::indexOf (Node * node) const
This method returns the array index of the specified pointer pointing to a Node object.
If it isn't contained in the array of child dnodes -1 is returned.
Author:
Bjoern
Definition at line 159 of file node.cpp.
References _children.
Referenced by Converter::_getNextSibling(), and Model::parent().
Node * Node::lastChild ()
This method returns a pointer to the last child node.
If the node has no children null is returned.
Author:
Bjoern
Definition at line 120 of file node.cpp.
References _children, and _cursor.
Node * Node::nextChild ()
This method returns a pointer to the next child node by moving the _cursor one step forward (increment of 1).
If the node has less than two children null is returned.
Author:
Bjoern
Definition at line 104 of file node.cpp.
References _children, and _cursor.
Referenced by Converter::_getNextChild().
void Node::removeChild (Node * node)
This method removes the specified pointer pointing to a Node object from the array of child nodes (_chidren).
Author:
Bjoern
Definition at line 151 of file node.cpp.
References _children, and _cursor.
Referenced by MainWindow::_treeViewRemoveNode(), and Converter::consume().
void Node::setContent (QString content)
This method sets the content of the node.
Author:
Bjoern
Definition at line 69 of file node.cpp.
References _content.
Referenced by Converter::consume(), and DocumentReader::readElement().
void Node::setName (QString name)
This method sets the name of the node.
Author:
Bjoern
Definition at line 61 of file node.cpp.
References _name.
void Node::setParent (Node * parent)
This method sets the pointer pointing to the parent node object.
Author:
Bjoern
Definition at line 79 of file node.cpp.
References _parent.
Referenced by addChild().
Member Data Documentation
QMap<QString, QString> Node::_attributes [private]
This is a key-value-structure which provides access to the value of type QString via keys of the type QString.
Author:
Bjoern
Definition at line 59 of file node.h.
Referenced by addAttribute(), getAttributes(), and Node().
QList<Node*> Node::_children [private]
This is generic array of pointers pointing to the child nodes.
Author:
Bjoern
Definition at line 54 of file node.h.
Referenced by addChild(), addChildren(), childAt(), containsChild(), firstChild(), getCount(), indexOf(), lastChild(), nextChild(), Node(), removeChild(), and ~Node().
QString Node::_content [private]
This is the content of the node.
Author:
Bjoern
Definition at line 46 of file node.h.
Referenced by getContent(), Node(), and setContent().
int Node::_cursor [private]
The _cursor indicates the current index position within the array of child nodes (_children).
The _cursor moves when the methods firstChild(), nextChild() and lastChild() are called.
Author:
Bjoern
Definition at line 65 of file node.h.
Referenced by firstChild(), lastChild(), nextChild(), and removeChild().
qint64 Node::_id [private]
The _id is a unique number which allows identification of the node.
Author:
Bjoern
Definition at line 32 of file node.h.
Referenced by containsChild(), getID(), and Node().
qint64 Node::_instCount = 0 [static, private]
The _instCount class member counts the created instances of the Node class.
Author:
Bjoern
Definition at line 19 of file node.h.
Referenced by Node().
qint64 Node::_layer [private]
The _layer numbers allows to determine to which layer / generation a node belongs.
The root node has the _layer number 0, its children 1 and its grand children 2 and so on.
Author:
Bjoern
Definition at line 38 of file node.h.
Referenced by getLayer(), and Node().
QString Node::_name [private]
This is the name of the node.
Author:
Bjoern
Definition at line 42 of file node.h.
Referenced by getName(), Node(), and setName().
Node* Node::_parent [private]
This pointer points to the parent node.
In case of the root node it points to null.
Author:
Bjoern
Definition at line 50 of file node.h.
Referenced by getParent(), Node(), and setParent().
qint64 Node::_treeLevel = 0 [static, private]
The _treeLevel attribute holds the greatest distance of a leaf to the root of the whole tree.
Author:
Bjoern
Definition at line 24 of file node.h.
Referenced by getTreeLevel(), and Node().
qint64 Node::_treeNodeCount [static, private]
The _treeNodeCount attribute holds the number of nodes of the whole tree.
Author:
Bjoern
Definition at line 28 of file node.h.
Referenced by getTreeNodeCount(), and Node().
The documentation for this class was generated from the following files:
node.h
node.cpp