htmLaTeX: Settings Class Reference
Settings Class Reference
This class stores settings variables for the application in a binary file.
#include <settings.h>
Public Member Functions
Settings ()
This constructor tries to load the settings from the binary file.
void setValue (QString key, QString value)
This method sets the specified variable to the given value.
QString getValue (QString key)
This method returns the value of the specified variable.
Static Public Attributes
static bool DEBUG = false
This class attribute is used to enable or disable "verbose-mode".
Private Member Functions
bool _load ()
This method tries to load the settings from the binary file.
bool _save ()
This method tries to save the settings to the binary file.
Private Attributes
const QString _SETTINGSFILEPATH
This is the binary file's file path.
QMap< QString, QString > _settingsMap
This is the associative array which stores the settings as key-value-pairs.
Detailed Description
This class stores settings variables for the application in a binary file.
The settings are stored in a key-value-pair data structure (an associative array). The class member DEBUG is used all over the application to provide additional information about the steps of the processings if desired (verbose). Saving to and loading from the binary file is performed "automatically". When a variable is requested or set the loading or saving is performed implicitly.
Definition at line 17 of file settings.h.
Constructor & Destructor Documentation
Settings::Settings ()
This constructor tries to load the settings from the binary file.
If it doesn't exist it is created with default settings.
Author:
Bjoern
Definition at line 3 of file settings.cpp.
References _load(), _save(), and _settingsMap.
Member Function Documentation
bool Settings::_load () [private]
This method tries to load the settings from the binary file.
Author:
Bjoern
Definition at line 18 of file settings.cpp.
References _SETTINGSFILEPATH, _settingsMap, and DEBUG.
Referenced by getValue(), and Settings().
bool Settings::_save () [private]
This method tries to save the settings to the binary file.
Author:
Bjoern
Definition at line 33 of file settings.cpp.
References _SETTINGSFILEPATH, and _settingsMap.
Referenced by Settings(), and setValue().
QString Settings::getValue (QString key)
This method returns the value of the specified variable.
Parameters:
<key> is the variable's name.
Author:
Bjoern
Definition at line 47 of file settings.cpp.
References _load(), _settingsMap, and DEBUG.
Referenced by MainWindow::_saveAs(), Converter::convert(), DocumentReader::DocumentReader(), main(), MainWindow::MainWindow(), DocumentReader::read(), and SettingsDialog::SettingsDialog().
void Settings::setValue (QString key, QString value)
This method sets the specified variable to the given value.
Parameters:
<key> is the variable's name.
Parameters:
<value> is the new variable's value.
Author:
Bjoern
Definition at line 59 of file settings.cpp.
References _save(), _settingsMap, and DEBUG.
Referenced by SettingsDialog::_apply(), and main().
Member Data Documentation
const QString Settings::_SETTINGSFILEPATH [private]
This is the binary file's file path.
This file contains the settings. If it doesn't exist it is created "automatically" with default settings.
Author:
Bjoern
Definition at line 35 of file settings.h.
Referenced by _load(), and _save().
QMap<QString,QString> Settings::_settingsMap [private]
This is the associative array which stores the settings as key-value-pairs.
Author:
Bjoern
Definition at line 39 of file settings.h.
Referenced by _load(), _save(), getValue(), Settings(), and setValue().
bool Settings::DEBUG = false [static]
This class attribute is used to enable or disable "verbose-mode".
Author:
Bjoern
Definition at line 29 of file settings.h.
Referenced by MainWindow::_convert(), _load(), MainWindow::_performInitialOperations(), DocumentData::_preprocessHTML(), DocumentReader::_readElement(), MainWindow::_saveAs(), Converter::consume(), Converter::convert(), TranslationMapper::createDocumentReaderData(), TranslationMapper::createOutputElementMap(), getValue(), DocumentReader::read(), and setValue().
The documentation for this class was generated from the following files:
settings.h
settings.cpp