htmLaTeX: TranslationData Class Reference
TranslationData Class Reference
The Converter performs the conversion on the application's internal tree structure.
#include <translationdata.h>
Public Member Functions
TranslationData ()
This is the only constructor which initializes the attributes.
QString key () const
This method returns the value of the _key attribute.
void setKey (QString key)
This method sets the value of the _key attribute.
QString from () const
This method returns the value of the _from attribute.
void setFrom (QString from)
This method sets the value of the _from attribute.
QString to () const
This method returns the value of the _to attribute.
void setTo (QString to)
This method sets the value of the _to attribute.
QList< TranslationDataNode > requires () const
This method returns the array of TranslationDataNode objects stored in the _requires attributes.
void addRequiresNode (TranslationDataNode requiresnode)
This method adds a TranslationDataNode object to the array of TranslationDataNode objects stored in the _requires attribute.
Private Attributes
QString _key
The _key is used by the TranslationMapper to store and access the TranslationData object in its _outputMap (an associative array).
QString _from
This attribute is unused yet.
QString _to
This attribute is the target string and can contain a place holder for further additions in the translation process.
QList< TranslationDataNode > _requires
This array of TranslationDataNode objects allows inclusion of special target document formatting instructions (i.e.
Detailed Description
The Converter performs the conversion on the application's internal tree structure.
In order to be able to translate each node of the internal tree the Converter retrieves a TranslationData object via the TranslationMapper. The Converter passes the name of that node which is currently to be translated as key to the TranslationMapper which returns the respective TranslationData object from its _outputMap (an associative array). This TranslationData object contains information which allow textual replacements on that node's content which is currently to be translated.
Definition at line 17 of file translationdata.h.
Constructor & Destructor Documentation
TranslationData::TranslationData ()
This is the only constructor which initializes the attributes.
Author:
Bjoern
Definition at line 3 of file translationdata.cpp.
References _requires.
Member Function Documentation
void TranslationData::addRequiresNode (TranslationDataNode requiresnode)
This method adds a TranslationDataNode object to the array of TranslationDataNode objects stored in the _requires attribute.
Author:
Bjoern
Definition at line 35 of file translationdata.cpp.
References _requires.
Referenced by TranslationMapper::createOutputElementMap().
QString TranslationData::from () const
This method returns the value of the _from attribute.
Author:
Bjoern
Definition at line 7 of file translationdata.cpp.
References _from.
QString TranslationData::key () const
This method returns the value of the _key attribute.
Author:
Bjoern
Definition at line 15 of file translationdata.cpp.
References _key.
Referenced by TranslationMapper::createOutputElementMap().
QList< TranslationDataNode > TranslationData::requires () const
This method returns the array of TranslationDataNode objects stored in the _requires attributes.
Author:
Bjoern
Definition at line 31 of file translationdata.cpp.
References _requires.
Referenced by Converter::_replace().
void TranslationData::setFrom (QString from)
This method sets the value of the _from attribute.
Author:
Bjoern
Definition at line 11 of file translationdata.cpp.
References _from.
Referenced by TranslationMapper::createOutputElementMap().
void TranslationData::setKey (QString key)
This method sets the value of the _key attribute.
Author:
Bjoern
Definition at line 19 of file translationdata.cpp.
References _key.
Referenced by TranslationMapper::createOutputElementMap().
void TranslationData::setTo (QString to)
This method sets the value of the _to attribute.
Author:
Bjoern
Definition at line 27 of file translationdata.cpp.
References _to.
Referenced by TranslationMapper::createOutputElementMap().
QString TranslationData::to () const
This method returns the value of the _to attribute.
Author:
Bjoern
Definition at line 23 of file translationdata.cpp.
References _to.
Referenced by Converter::_replace().
Member Data Documentation
QString TranslationData::_from [private]
This attribute is unused yet.
Author:
Bjoern
Definition at line 33 of file translationdata.h.
Referenced by from(), and setFrom().
QString TranslationData::_key [private]
The _key is used by the TranslationMapper to store and access the TranslationData object in its _outputMap (an associative array).
Author:
Bjoern
Definition at line 29 of file translationdata.h.
Referenced by key(), and setKey().
QList<TranslationDataNode> TranslationData::_requires [private]
This array of TranslationDataNode objects allows inclusion of special target document formatting instructions (i.e.
"requires" in TEX).
Definition at line 42 of file translationdata.h.
Referenced by addRequiresNode(), requires(), and TranslationData().
QString TranslationData::_to [private]
This attribute is the target string and can contain a place holder for further additions in the translation process.
Author:
Bjoern
Definition at line 38 of file translationdata.h.
Referenced by setTo(), and to().
The documentation for this class was generated from the following files:
translationdata.h
translationdata.cpp