htmLaTeX: TranslationMapper Class Reference
TranslationMapper Class Reference
This class processes the input and output definition files to procure data structures which meet the needs of the DocumentReader and Converter classes.
#include <translationmapper.h>
Public Member Functions
TranslationMapper (QObject *parent=0)
This is the only constructor.
void createDocumentReaderData (QString inputfilepath)
This method processes the input definition file to store a DocumentReaderData object in the attribute _documentReference.
void createOutputElementMap (QString outputfilepath)
This method processes the output definition file to populate the attribute _outputMap with a TranslationData object for each different node of the input document.
DocumentReaderData getDocumentReference () const
This method returns the object held by the attribute _documentReference.
QMap< QString, TranslationData > outputMap () const
This method returns the object held by the attribute _outputMap.
Private Attributes
DocumentReaderData _documentReference
This attribute contains a DocumentReaderData object which describes how a reference to a subdocument of an input document is defined.
QMap< QString, TranslationData > _outputMap
This attribute holds a key-value-pair data structure (an associative array).
Detailed Description
This class processes the input and output definition files to procure data structures which meet the needs of the DocumentReader and Converter classes.
Hence it creates a DocumentReaderData object stored in the _documentReference attribute which describes how a reference to a subdocument of an input document is defined. In addition it creates a key-value-pair data structure (an associative array) which holds information about how the relevant nodes of the input document are to be translated.
Author:
Bjoern
Definition at line 23 of file translationmapper.h.
Constructor & Destructor Documentation
TranslationMapper::TranslationMapper (QObject * parent = 0)
This is the only constructor.
Author:
Bjoern
Definition at line 3 of file translationmapper.cpp.
Member Function Documentation
void TranslationMapper::createDocumentReaderData (QString inputfilepath)
This method processes the input definition file to store a DocumentReaderData object in the attribute _documentReference.
Parameters:
<inputfilepath> is the file path to the input definition file.
Author:
Bjoern
Definition at line 6 of file translationmapper.cpp.
References _documentReference, and Settings::DEBUG.
Referenced by MainWindow::_performInitialOperations(), Console::_performInitialOperations(), and MainWindow::_setInputDefinition().
void TranslationMapper::createOutputElementMap (QString outputfilepath)
This method processes the output definition file to populate the attribute _outputMap with a TranslationData object for each different node of the input document.
Parameters:
<outputfilepath> is the file path to the output definition file.
Author:
Bjoern
Definition at line 44 of file translationmapper.cpp.
References _outputMap, TranslationDataNode::addAttribute(), TranslationData::addRequiresNode(), Settings::DEBUG, TranslationData::key(), TranslationDataNode::setContent(), TranslationData::setFrom(), TranslationData::setKey(), TranslationDataNode::setName(), and TranslationData::setTo().
Referenced by MainWindow::_performInitialOperations(), Console::_performInitialOperations(), and MainWindow::_setOutputDefinition().
DocumentReaderData TranslationMapper::getDocumentReference () const
This method returns the object held by the attribute _documentReference.
Author:
Bjoern
Definition at line 110 of file translationmapper.cpp.
References _documentReference.
Referenced by DocumentReader::_readElement().
QMap< QString, TranslationData > TranslationMapper::outputMap () const
This method returns the object held by the attribute _outputMap.
Author:
Bjoern
Definition at line 114 of file translationmapper.cpp.
References _outputMap.
Referenced by Converter::_replace().
Member Data Documentation
DocumentReaderData TranslationMapper::_documentReference [private]
This attribute contains a DocumentReaderData object which describes how a reference to a subdocument of an input document is defined.
Author:
Bjoern
Definition at line 36 of file translationmapper.h.
Referenced by createDocumentReaderData(), and getDocumentReference().
QMap<QString,TranslationData> TranslationMapper::_outputMap [private]
This attribute holds a key-value-pair data structure (an associative array).
The items of this array can be accessed via a key of the type QString (i.e. _outputMap["head"]). The node names of the input document serve as keys for this array. The received value is a TranslationData object providing information for the Converter which performs textual replacements.
Author:
Bjoern
Definition at line 44 of file translationmapper.h.
Referenced by createOutputElementMap(), and outputMap().
The documentation for this class was generated from the following files:
translationmapper.h
translationmapper.cpp