htmLaTeX: SettingsDialog Class Reference
SettingsDialog Class Reference
The SettingsDialog provides a convenient way to change the application's settings such as the language or the inclusion of subdocuments.
#include <settingsdialog.h>
Signals
void languageChanged (QLocale::Country language)
This signal is connected to mainWindow and is raised when the user applies settings.
Public Member Functions
SettingsDialog (QWidget *parent=0)
This is the only constructor which initializes the GUI.
~SettingsDialog ()
This is the destructor.
void retranslateUi ()
This method is called by the mainWindow's _languageChanged slot after the mainWindow's _translator has been switched to another language.
Private Slots
void _apply ()
This slot is called when the user clicks the push button "apply".
void _open ()
This slot is called when the user clicks the push button "browse".
Private Attributes
Ui::SettingsDialog * ui
This declaration allows access to the separated GUI source code via the short label ui.
Detailed Description
The SettingsDialog provides a convenient way to change the application's settings such as the language or the inclusion of subdocuments.
It makes use of the Settings class to laod the settings from and save them to a binary file.
Author:
Bjoern
Definition at line 25 of file settingsdialog.h.
Constructor & Destructor Documentation
SettingsDialog::SettingsDialog (QWidget * parent = 0)
This is the only constructor which initializes the GUI.
Author:
Bjoern
Definition at line 4 of file settingsdialog.cpp.
References _apply(), _open(), Settings::getValue(), and ui.
SettingsDialog::~SettingsDialog ()
This is the destructor.
Author:
Bjoern
Definition at line 25 of file settingsdialog.cpp.
References ui.
Member Function Documentation
void SettingsDialog::_apply () [private, slot]
This slot is called when the user clicks the push button "apply".
Author:
Bjoern
Definition at line 29 of file settingsdialog.cpp.
References languageChanged(), Settings::setValue(), and ui.
Referenced by SettingsDialog().
void SettingsDialog::_open () [private, slot]
This slot is called when the user clicks the push button "browse".
Author:
Bjoern
Definition at line 62 of file settingsdialog.cpp.
References ui.
Referenced by SettingsDialog().
void SettingsDialog::languageChanged (QLocale::Country language) [signal]
This signal is connected to mainWindow and is raised when the user applies settings.
It triggers the retranslation of the application's texts.
Parameters:
<language> contains the information to which language mainWindow's _translator is supposed to translate.
Author:
Bjoern
Referenced by _apply().
void SettingsDialog::retranslateUi ()
This method is called by the mainWindow's _languageChanged slot after the mainWindow's _translator has been switched to another language.
It triggers the retranslation of the SettingsDialog's texts.
Author:
Bjoern
Definition at line 73 of file settingsdialog.cpp.
References ui.
Referenced by MainWindow::_languageChanged().
Member Data Documentation
Ui::SettingsDialog* SettingsDialog::ui [private]
This declaration allows access to the separated GUI source code via the short label ui.
Author:
Bjoern
Definition at line 42 of file settingsdialog.h.
Referenced by _apply(), _open(), retranslateUi(), SettingsDialog(), and ~SettingsDialog().
The documentation for this class was generated from the following files:
settingsdialog.h
settingsdialog.cpp