htmLaTeX: CConsole Class Reference
CConsole Class Reference
This class provides the command line functionality of the application.
#include <cconsole.h>
Public Member Functions
CConsole (QStringList arguments, QStringList options)
~CConsole ()
Private Member Functions
void _performInitialOperations (QStringList arguments, QStringList options)
Detailed Description
This class provides the command line functionality of the application.
Author:
Bjoern
Definition at line 14 of file cconsole.h.
Constructor & Destructor Documentation
CConsole::CConsole (QStringList arguments, QStringList options)
Definition at line 4 of file cconsole.cpp.
References _performInitialOperations().
CConsole::~CConsole ()
Definition at line 8 of file cconsole.cpp.
Member Function Documentation
void CConsole::_performInitialOperations (QStringList arguments, QStringList options) [private]
Definition at line 14 of file cconsole.cpp.
References CConverter::convert(), CTranslationMapper::createInputElementMap(), CTranslationMapper::createOutputElementMap(), CDocumentData::JavaDocHTML, CDocumentReader::read(), CDocumentData::Tex, and CDocumentData::Unknown.
Referenced by CConsole().
The documentation for this class was generated from the following files:
/home/bjoern/projekt/htmlatex/cconsole.h
/home/bjoern/projekt/htmlatex/cconsole.cpp