htmLaTeX: CTranslationMapper Class Reference
CTranslationMapper Class Reference
#include <ctranslationmapper.h>
Public Member Functions
void createInputElementMap (QString inputfilepath)
void createOutputElementMap (QString outputfilepath)
QMap< QString, CTranslationData > outputMap () const
CTranslationMapper ()
Private Attributes
QMap< QString, CTranslationData > _outputMap
Detailed Description
Definition at line 13 of file ctranslationmapper.h.
Constructor & Destructor Documentation
CTranslationMapper::CTranslationMapper ()
Definition at line 3 of file ctranslationmapper.cpp.
References _outputMap.
Member Function Documentation
void CTranslationMapper::createInputElementMap (QString inputfilepath)
Definition at line 7 of file ctranslationmapper.cpp.
Referenced by MainWindow::_performInitialOperations(), CConsole::_performInitialOperations(), and MainWindow::_setInputDefinition().
void CTranslationMapper::createOutputElementMap (QString outputfilepath)
Definition at line 10 of file ctranslationmapper.cpp.
References _outputMap, CTranslationDataNode::addAttribute(), CTranslationData::addRequiresNode(), Settings::DEBUG, CTranslationData::key(), CTranslationDataNode::setContent(), CTranslationData::setFrom(), CTranslationData::setKey(), CTranslationDataNode::setName(), and CTranslationData::setTo().
Referenced by MainWindow::_performInitialOperations(), CConsole::_performInitialOperations(), and MainWindow::_setOutputDefinition().
QMap< QString, CTranslationData > CTranslationMapper::outputMap () const
Definition at line 76 of file ctranslationmapper.cpp.
References _outputMap.
Referenced by CConverter::_replace().
Member Data Documentation
QMap<QString,CTranslationData> CTranslationMapper::_outputMap [private]
Definition at line 16 of file ctranslationmapper.h.
Referenced by createOutputElementMap(), CTranslationMapper(), and outputMap().
The documentation for this class was generated from the following files:
/home/bjoern/projekt/htmlatex/ctranslationmapper.h
/home/bjoern/projekt/htmlatex/ctranslationmapper.cpp