htmLaTeX: Console Class Reference
Console Class Reference
This class provides the command line functionality of the application.
#include <console.h>
Public Member Functions
Console (QStringList arguments, QStringList options)
This is the only constructor.
Private Member Functions
void _performInitialOperations (QStringList arguments, QStringList options)
This method processes the application's startup arguments and performs the conversion by means of a DocumentReader and a Converter object.
Detailed Description
This class provides the command line functionality of the application.
Author:
Bjoern
Definition at line 14 of file console.h.
Constructor & Destructor Documentation
Console::Console (QStringList arguments, QStringList options)
This is the only constructor.
Parameters:
<arguments> is an array of strings which contains the startup arguments of the application except the executable file's name and optional paramters.
Parameters:
<options> is an array of strings which contains just the optional startup arguments of the application.
Author:
Bjoern
Definition at line 3 of file console.cpp.
References _performInitialOperations().
Member Function Documentation
void Console::_performInitialOperations (QStringList arguments, QStringList options) [private]
This method processes the application's startup arguments and performs the conversion by means of a DocumentReader and a Converter object.
This method processes the application's startup arguments and performs the conversion by means of a DocumentReader and Converter object.
Parameters:
<arguments> is an array of strings which contains the startup arguments of the application except the executable file's name and optional paramters.
Parameters:
<options> is an array of strings which contains just the optional startup arguments of the application.
Author:
Bjoern
Bjoern
Definition at line 11 of file console.cpp.
References Converter::convert(), TranslationMapper::createDocumentReaderData(), TranslationMapper::createOutputElementMap(), DocumentData::JavaDocHTML, DocumentData::PDF, DocumentReader::read(), DocumentData::Tex, and DocumentData::Unknown.
Referenced by Console().
The documentation for this class was generated from the following files:
console.h
console.cpp