htmLaTeX: Converter Class Reference
Converter Class Reference
This class converts the QDomDocument-Tree to a textfile by performing the conversions descibed in the 'Output-Definition'-XML file.
#include <converter.h>
Signals
void updateTextEdit (QString text)
void updateProgressBar (int percentage)
Public Member Functions
Converter (QObject *parent, TranslationMapper *translationmapper)
Constructor.
void convert (const QString filepath, Node *root)
converts to QString and writes the output file
Private Types
enum DocumentPosition { start, content, end }
the compiler assigns values for start, content and end
Private Member Functions
Node * getLeaf (Node *node=_cursor)
retrieves the first leaf of the tree
bool isLeaf (Node *node=_cursor)
Is the node a leaf?
QMap< QString, QString > getAttributes (Node *node=_cursor)
returns the node's attributes
QString getContent (Node *node=_cursor)
returns the node's content
QString getName (Node *node=_cursor)
returns the node's name
bool consume (Node *node=_cursor)
Writes the information of the current (leaf) node into the parent, deletes the active node and sets the cursor to the next leaf.
int match (QString content, QString pattern)
Node * _getNextSibling ()
gets the next sibling
Node * _getNextChild ()
gets the next child
Node * _getNextNode ()
get the next node in the tree if no siblings left it gets the next child
qint64 _getTreeLevel ()
get the Level ot the current node
QString _peekParent (qint32 distance)
gets the key of the parent node <distance> levels up the tree
QBool _isEmpty ()
true if string is empty
QBool _isEmptyContent ()
true if content is empty
void removeToken ()
removes tokens e.g.
void _consume ()
true if started as GUI only necessary if the view(Editor part of the GUI) or a progressbar has to receive extra information
void _write (QString content, qint32 part)
writes <content> at the end of the desired <part>
qint64 _tryMatch (QString pattern)
returns offset if <pattern> is found otherwise returns "-1"
QString _replace (Node *node=_cursor)
replaces place holder with the content of the current node
Private Attributes
QFile _file
outputfile
QTextStream _stream
outputfilestream
Node * _root
the root node
TranslationMapper * _translationMapper
QString _errormessage
qint32 _noOfParts
QStringList replacementMarks
QStringList _parts
Static Private Attributes
static Node * _cursor = 0
the active node
Detailed Description
This class converts the QDomDocument-Tree to a textfile by performing the conversions descibed in the 'Output-Definition'-XML file.
Author:
Bjoern
Version:
0.1
Definition at line 20 of file converter.h.
Member Enumeration Documentation
enum Converter::DocumentPosition [private]
the compiler assigns values for start, content and end
Enumerator:
start
content
end
Definition at line 55 of file converter.h.
Constructor & Destructor Documentation
Converter::Converter (QObject * parent, TranslationMapper * translationmapper)
Constructor.
Parameters:
<filepath> where to write the output
Parameters:
<root> the root-node of the QDomDocument to convert from TODO:
Parameters:
<parts> the number of parts that are needed for the conversion use enum{start=0, content=1, end=2} (change the XML aliases to numbers)
Definition at line 3 of file converter.cpp.
References _root, _translationMapper, and replacementMarks.
Member Function Documentation
void Converter::_consume () [private]
true if started as GUI only necessary if the view(Editor part of the GUI) or a progressbar has to receive extra information
delete node and set cursor to the next node
Node * Converter::_getNextChild () [private]
gets the next child
Definition at line 130 of file converter.cpp.
References _cursor, and Node::nextChild().
Node * Converter::_getNextNode () [private]
get the next node in the tree if no siblings left it gets the next child
Definition at line 135 of file converter.cpp.
Node * Converter::_getNextSibling () [private]
gets the next sibling
Definition at line 118 of file converter.cpp.
References _cursor, Node::childAt(), Node::getCount(), Node::getParent(), and Node::indexOf().
qint64 Converter::_getTreeLevel () [private]
get the Level ot the current node
Definition at line 142 of file converter.cpp.
References _root, and Node::getTreeLevel().
QBool Converter::_isEmpty () [private]
true if string is empty
Definition at line 155 of file converter.cpp.
QBool Converter::_isEmptyContent () [private]
true if content is empty
Definition at line 160 of file converter.cpp.
References _cursor, and Node::getContent().
QString Converter::_peekParent (qint32 distance) [private]
gets the key of the parent node <distance> levels up the tree
Definition at line 148 of file converter.cpp.
QString Converter::_replace (Node * node = _cursor) [private]
replaces place holder with the content of the current node
Definition at line 176 of file converter.cpp.
References _translationMapper, Node::getContent(), Node::getName(), TranslationMapper::outputMap(), replacementMarks, TranslationData::requires(), and TranslationData::to().
Referenced by consume().
qint64 Converter::_tryMatch (QString pattern) [private]
returns offset if <pattern> is found otherwise returns "-1"
Definition at line 171 of file converter.cpp.
void Converter::_write (QString content, qint32 part) [private]
writes <content> at the end of the desired <part>
Definition at line 168 of file converter.cpp.
bool Converter::consume (Node * node = _cursor) [private]
Writes the information of the current (leaf) node into the parent, deletes the active node and sets the cursor to the next leaf.
Definition at line 86 of file converter.cpp.
References _cursor, _replace(), getLeaf(), Node::getParent(), match(), Node::removeChild(), replacementMarks, and Node::setContent().
Referenced by convert().
void Converter::convert (const QString filepath, Node * root)
converts to QString and writes the output file
Parameters:
<qint32> the number of parts in the outputDocument
Definition at line 18 of file converter.cpp.
References _cursor, consume(), Settings::DEBUG, Node::getContent(), Node::getCount(), getLeaf(), Node::getTreeNodeCount(), updateProgressBar(), and updateTextEdit().
Referenced by MainWindow::_convert(), MainWindow::_performInitialOperations(), and Console::_performInitialOperations().
QMap< QString, QString > Converter::getAttributes (Node * node = _cursor) [private]
returns the node's attributes
Definition at line 74 of file converter.cpp.
References Node::getAttributes().
QString Converter::getContent (Node * node = _cursor) [private]
returns the node's content
Definition at line 78 of file converter.cpp.
References Node::getContent().
Node * Converter::getLeaf (Node * node = _cursor) [private]
retrieves the first leaf of the tree
Definition at line 63 of file converter.cpp.
References Node::firstChild().
Referenced by consume(), and convert().
QString Converter::getName (Node * node = _cursor) [private]
returns the node's name
Definition at line 82 of file converter.cpp.
References Node::getName().
bool Converter::isLeaf (Node * node = _cursor) [private]
Is the node a leaf?
Definition at line 70 of file converter.cpp.
References Node::getCount().
int Converter::match (QString content, QString pattern) [private]
Definition at line 195 of file converter.cpp.
Referenced by consume().
void Converter::removeToken () [private]
removes tokens e.g.
"----CONTENT----"
Definition at line 165 of file converter.cpp.
void Converter::updateProgressBar (int percentage) [signal]
Referenced by convert().
void Converter::updateTextEdit (QString text) [signal]
Referenced by convert().
Member Data Documentation
Node * Converter::_cursor = 0 [static, private]
the active node
Definition at line 49 of file converter.h.
Referenced by _getNextChild(), _getNextSibling(), _isEmptyContent(), consume(), and convert().
QString Converter::_errormessage [private]
Definition at line 50 of file converter.h.
QFile Converter::_file [private]
outputfile
Definition at line 42 of file converter.h.
qint32 Converter::_noOfParts [private]
Definition at line 51 of file converter.h.
QStringList Converter::_parts [private]
Definition at line 59 of file converter.h.
Node* Converter::_root [private]
the root node
Definition at line 46 of file converter.h.
Referenced by _getTreeLevel(), and Converter().
QTextStream Converter::_stream [private]
outputfilestream
Definition at line 44 of file converter.h.
TranslationMapper* Converter::_translationMapper [private]
Definition at line 47 of file converter.h.
Referenced by _replace(), and Converter().
QStringList Converter::replacementMarks [private]
Definition at line 52 of file converter.h.
Referenced by _replace(), consume(), and Converter().
The documentation for this class was generated from the following files:
converter.h
converter.cpp