htmLaTeX: MainWindow Class Reference
MainWindow Class Reference
This is the central class of the GUI application.
#include <mainwindow.h>
Public Member Functions
MainWindow (QStringList arguments, QStringList options, QWidget *parent)
This is the only constructor.
~MainWindow ()
This is the destructor.
Private Slots
void _languageChanged (QLocale::Country language)
This slot is connected to _settingsDialog and is called when the user applies settings.
void _open ()
This slot is called when the user clicks the menu item or tool bar button for "open".
void _convert ()
This slot is called when the user clicks the menu item or tool bar button for "convert".
void _setInputDefinition ()
This slot is called when the user clicks the menu item or tool bar button for "set input definition".
void _setOutputDefinition ()
This slot is called when the user clicks the menu item or tool bar button for "set output definition".
void _showSettings ()
This slot is called when the user clicks the menu item or tool bar button for "settings".
void _about ()
This slot is called when the user clicks the menu item or tool bar button for "about".
void _showTreeViewContextMenu (QPoint point)
This slot is called when the user clicks the right mouse button on the _treeView to show the context menu.
void _treeViewRemoveNode ()
This slot is called when the user chooses to remove a node from the treeView.
void _updateProgressBar (int percentage)
This slot is connected to the _converter.
Private Member Functions
void _performInitialOperations (QStringList arguments, QStringList options)
This method performs opening and converting operations depending on the application's startup arguments.
Private Attributes
Ui::MainWindow * ui
This declaration allows access to the separated GUI source code via the short label ui.
Model * _model
The model is the data source of the treeView.
ItemDelegate * _itemDelegate
The _itemDelegate controls how the treeView displays data.
SettingsDialog * _settingsDialog
The _settingsDialog is a modal dialog whose settings are saved to a binary file.
QTranslator _translator
The _translator translates the application's texts.
TranslationMapper * _translationMapper
The _translationMapper provides two data objects: firstly a DocumentReaderData object which is used by the DocumentReader and secondly a key-value-pair structure which is used by the Converter.
Converter * _converter
The _converter converts the internal tree structure.
Detailed Description
This is the central class of the GUI application.
The treeView on the left hand side displays the opened document as a tree structure and allows modification via context menu. The textEdit on the right hand side displays the conversion output and can be edited directly.
Author:
Bjoern
Definition at line 28 of file mainwindow.h.
Constructor & Destructor Documentation
MainWindow::MainWindow (QStringList arguments, QStringList options, QWidget * parent)
This is the only constructor.
of the application except the executable file's name and optional paramters.
Parameters:
arguments is an array of strings which contains the startup argument of the application except the executable file's name and optional paramters.
Parameters:
options is an array of strings which contains just the optional startup arguments of the application.
Parameters:
parent is a pointer pointing to the parent widget (QDialog and QMainWindow are derived from QWidget).
Author:
Bjoern
Parameters:
options is an array of strings which contains just the optional startup arguments of the application.
Parameters:
parent is a pointer pointing to the parent widget (QDialog and QMainWindow are derived from QWidget).
Author:
Bjoern
Definition at line 10 of file mainwindow.cpp.
References _about(), _convert(), _converter, _itemDelegate, _languageChanged(), _model, _open(), _performInitialOperations(), _setInputDefinition(), _setOutputDefinition(), _settingsDialog, _showSettings(), _showTreeViewContextMenu(), _translationMapper, _treeViewRemoveNode(), _updateProgressBar(), Settings::getValue(), and ui.
MainWindow::~MainWindow ()
This is the destructor.
Definition at line 61 of file mainwindow.cpp.
References _converter, _translationMapper, and ui.
Member Function Documentation
void MainWindow::_about () [private, slot]
This slot is called when the user clicks the menu item or tool bar button for "about".
Author:
Bjoern
Definition at line 285 of file mainwindow.cpp.
Referenced by MainWindow().
void MainWindow::_convert () [private, slot]
This slot is called when the user clicks the menu item or tool bar button for "convert".
Author:
Bjoern
Definition at line 227 of file mainwindow.cpp.
References _converter, _model, Converter::convert(), Settings::DEBUG, DocumentData::JavaDocHTML, Model::root(), DocumentData::Tex, and DocumentData::Unknown.
Referenced by MainWindow().
void MainWindow::_languageChanged (QLocale::Country language) [private, slot]
This slot is connected to _settingsDialog and is called when the user applies settings.
supposed to translate.
It triggers the retranslation of the application's texts.
Parameters:
language contains the information to which language the _translator is supposed to translate.
Author:
Bjoern
Bjoern
Definition at line 194 of file mainwindow.cpp.
References _settingsDialog, _translator, SettingsDialog::retranslateUi(), and ui.
Referenced by MainWindow().
void MainWindow::_open () [private, slot]
This slot is called when the user clicks the menu item or tool bar button for "open".
Author:
Bjoern
Definition at line 205 of file mainwindow.cpp.
References _model, _translationMapper, DocumentData::JavaDocHTML, DocumentReader::read(), Model::setRootNode(), and DocumentData::Unknown.
Referenced by MainWindow().
void MainWindow::_performInitialOperations (QStringList arguments, QStringList options) [private]
This method performs opening and converting operations depending on the application's startup arguments.
of the application except the executable file's name and optional paramters.
Parameters:
arguments is an array of strings which contains the startup argument of the application except the executable file's name and optional paramters.
Parameters:
options is an array of strings which contains just the optional startup arguments of the application.
Author:
Bjoern
Parameters:
options is an array of strings which contains just the optional startup arguments of the application.
Author:
Bjoern
arguments: 0 = source file path 1 = source file type 2 = input definition file path 3 = target file path 4 = target file type 5 = output definition file path
Definition at line 71 of file mainwindow.cpp.
References _converter, _model, _translationMapper, Converter::convert(), TranslationMapper::createDocumentReaderData(), TranslationMapper::createOutputElementMap(), Settings::DEBUG, Node::getCount(), DocumentData::JavaDocHTML, DocumentReader::read(), Model::root(), Model::setRootNode(), DocumentData::Tex, and DocumentData::Unknown.
Referenced by MainWindow().
void MainWindow::_setInputDefinition () [private, slot]
This slot is called when the user clicks the menu item or tool bar button for "set input definition".
Author:
Bjoern
Definition at line 265 of file mainwindow.cpp.
References _translationMapper, and TranslationMapper::createDocumentReaderData().
Referenced by MainWindow().
void MainWindow::_setOutputDefinition () [private, slot]
This slot is called when the user clicks the menu item or tool bar button for "set output definition".
Author:
Bjoern
Definition at line 273 of file mainwindow.cpp.
References _translationMapper, and TranslationMapper::createOutputElementMap().
Referenced by MainWindow().
void MainWindow::_showSettings () [private, slot]
This slot is called when the user clicks the menu item or tool bar button for "settings".
Author:
Bjoern
Definition at line 281 of file mainwindow.cpp.
References _settingsDialog.
Referenced by MainWindow().
void MainWindow::_showTreeViewContextMenu (QPoint point) [private, slot]
This slot is called when the user clicks the right mouse button on the _treeView to show the context menu.
Author:
Bjoern
Definition at line 291 of file mainwindow.cpp.
References _model, Model::nodeFromIndex(), and ui.
Referenced by MainWindow().
void MainWindow::_treeViewRemoveNode () [private, slot]
This slot is called when the user chooses to remove a node from the treeView.
Author:
Bjoern
Definition at line 301 of file mainwindow.cpp.
References _model, Node::getLayer(), Node::getParent(), Model::nodeFromIndex(), Model::refresh(), Node::removeChild(), and ui.
Referenced by MainWindow().
void MainWindow::_updateProgressBar (int percentage) [private, slot]
This slot is connected to the _converter.
Author:
Bjoern
Definition at line 313 of file mainwindow.cpp.
References ui.
Referenced by MainWindow().
Member Data Documentation
Converter* MainWindow::_converter [private]
The _converter converts the internal tree structure.
Author:
Bjoern
Definition at line 80 of file mainwindow.h.
Referenced by _convert(), _performInitialOperations(), MainWindow(), and ~MainWindow().
ItemDelegate* MainWindow::_itemDelegate [private]
The _itemDelegate controls how the treeView displays data.
The ItemDelegate class is derived from the QItemDelegate class. Its paint() method influences the drawing of the widget directly.
Author:
Bjoern
Definition at line 61 of file mainwindow.h.
Referenced by MainWindow().
Model* MainWindow::_model [private]
The model is the data source of the treeView.
The Model class is derived from the abstract class QAbstractItemModel and provides the functionality that a QTreeView object demands in order to display data.
Author:
Bjoern
Definition at line 55 of file mainwindow.h.
Referenced by _convert(), _open(), _performInitialOperations(), _showTreeViewContextMenu(), _treeViewRemoveNode(), and MainWindow().
SettingsDialog* MainWindow::_settingsDialog [private]
The _settingsDialog is a modal dialog whose settings are saved to a binary file.
Author:
Bjoern
Definition at line 66 of file mainwindow.h.
Referenced by _languageChanged(), _showSettings(), and MainWindow().
TranslationMapper* MainWindow::_translationMapper [private]
The _translationMapper provides two data objects: firstly a DocumentReaderData object which is used by the DocumentReader and secondly a key-value-pair structure which is used by the Converter.
Author:
Bjoern
Definition at line 76 of file mainwindow.h.
Referenced by _open(), _performInitialOperations(), _setInputDefinition(), _setOutputDefinition(), MainWindow(), and ~MainWindow().
QTranslator MainWindow::_translator [private]
The _translator translates the application's texts.
Author:
Bjoern
Definition at line 70 of file mainwindow.h.
Referenced by _languageChanged().
Ui::MainWindow* MainWindow::ui [private]
This declaration allows access to the separated GUI source code via the short label ui.
Author:
Bjoern
Definition at line 49 of file mainwindow.h.
Referenced by _languageChanged(), _showTreeViewContextMenu(), _treeViewRemoveNode(), _updateProgressBar(), MainWindow(), and ~MainWindow().
The documentation for this class was generated from the following files:
mainwindow.h
mainwindow.cpp