htmLaTeX: DocumentReaderData Class Reference
DocumentReaderData Class Reference
This class describes how a reference to a subdocument of an input document is defined.
#include <documentreaderdata.h>
Public Member Functions
DocumentReaderData ()
This is an empty constructor which initializes the attributes _tagName and _urlContainingAttributeName with empty strings.
DocumentReaderData (const DocumentReaderData &documentreaderdata)
This is the copy constructor.
DocumentReaderData (QString tagname, QString urlcontainingattributename)
This constructor initializes the attributes _tagName and _urlContainingAttributeName with the given string values.
QString getTagName () const
This method returns the name of that XML tag which decribes a reference to a subdocument in the XML represented input document.
QString getUrlContainingAttributeName () const
This method returns the name of that XML attribute belonging to the XML tag specified by _tagName and which holds the file path to a subdocument in the XML represented input document.
Private Attributes
QString _tagName
This attribute contains the name of that XML tag which decribes a reference to a subdocument in the XML represented input document.
QString _urlContainingAttributeName
This attribute contains the name of that XML attribute belonging to the XML tag specified by _tagName and which holds the file path to a subdocument in the XML represented input document.
Detailed Description
This class describes how a reference to a subdocument of an input document is defined.
Example: In (X)HTML a subdocumet is referenced using the tag with its attribute "href". The TranslationMapper creates an instance of the DocumentReaderData class using the document definition file. Finally the DocumentReader obtains the DocumentReaderData object from the TranslationMapper.
Author:
Bjoern
Definition at line 14 of file documentreaderdata.h.
Constructor & Destructor Documentation
DocumentReaderData::DocumentReaderData ()
This is an empty constructor which initializes the attributes _tagName and _urlContainingAttributeName with empty strings.
Author:
Bjoern
Definition at line 3 of file documentreaderdata.cpp.
DocumentReaderData::DocumentReaderData (const DocumentReaderData & documentreaderdata)
This is the copy constructor.
Author:
Bjoern
Definition at line 7 of file documentreaderdata.cpp.
References _tagName, _urlContainingAttributeName, getTagName(), and getUrlContainingAttributeName().
DocumentReaderData::DocumentReaderData (QString tagname, QString urlcontainingattributename)
This constructor initializes the attributes _tagName and _urlContainingAttributeName with the given string values.
Parameters:
<tagname> contains a XML tag name.
Parameters:
<urlcontainingattributename> contains a XML attribute name.
Author:
Bjoern
Definition at line 12 of file documentreaderdata.cpp.
References _tagName, and _urlContainingAttributeName.
Member Function Documentation
QString DocumentReaderData::getTagName () const
This method returns the name of that XML tag which decribes a reference to a subdocument in the XML represented input document.
Author:
Bjoern
Definition at line 17 of file documentreaderdata.cpp.
References _tagName.
Referenced by DocumentReader::_readElement(), and DocumentReaderData().
QString DocumentReaderData::getUrlContainingAttributeName () const
This method returns the name of that XML attribute belonging to the XML tag specified by _tagName and which holds the file path to a subdocument in the XML represented input document.
Author:
Bjoern
Definition at line 21 of file documentreaderdata.cpp.
References _urlContainingAttributeName.
Referenced by DocumentReader::_readElement(), and DocumentReaderData().
Member Data Documentation
QString DocumentReaderData::_tagName [private]
This attribute contains the name of that XML tag which decribes a reference to a subdocument in the XML represented input document.
Author:
Bjoern
Definition at line 38 of file documentreaderdata.h.
Referenced by DocumentReaderData(), and getTagName().
QString DocumentReaderData::_urlContainingAttributeName [private]
This attribute contains the name of that XML attribute belonging to the XML tag specified by _tagName and which holds the file path to a subdocument in the XML represented input document.
Author:
Bjoern
Definition at line 44 of file documentreaderdata.h.
Referenced by DocumentReaderData(), and getUrlContainingAttributeName().
The documentation for this class was generated from the following files:
documentreaderdata.h
documentreaderdata.cpp